export const PRESET_CLIENT_COLUMNS = [
  // בסיס (קיימים כבר בישות) - לא מוסיף ברירת מחדל, רק כעוגן UI
  { slug: "name", label: "שם לקוח", type: "text", group: "פרטי לקוח", builtin: true },
  { slug: "stage", label: "שלבים", type: "stage", group: "פרטי לקוח", builtin: true },
  { slug: "phone", label: "טלפון", type: "text", group: "פרטי לקוח", builtin: true },
  { slug: "email", label: "מייל", type: "text", group: "פרטי לקוח", builtin: true },

  // שדות מותאמים - ישמרו תחת client.custom_data[slug]
  { slug: "block", label: "גוש", type: "text", group: "מקרקעין" },
  { slug: "lot", label: "מגרש", type: "text", group: "מקרקעין" },
  { slug: "parcel", label: "חלקה", type: "text", group: "מקרקעין" },
  { slug: "price_estimate", label: "ה.מחיר", type: "text", group: "כספים" },
  { slug: "price_estimate_signed", label: "ה.מחיר חתומה", type: "boolean", group: "כספים" },
  { slug: "down_payment", label: "תשלום מקדמה", type: "boolean", group: "כספים" },
  { slug: "poa_manager", label: "יפוי כוח למנהל", type: "boolean", group: "מסמכים" },
  { slug: "poa_general", label: "יפוי כוח כללי", type: "boolean", group: "מסמכים" },
  { slug: "feasibility_rights_check", label: "בדיקת היתכנות וזכויות בניה", type: "boolean", group: "בדיקות" },
  { slug: "manager_docs_disk_ordered", label: "הזמנת דיסק מסמכים מהמנהל", type: "boolean", group: "מסמכים" },
  { slug: "photos", label: "תמונות", type: "text", group: "מסמכים" },
  { slug: "trees_avoid_measure", label: "עצים (להמנע ממדידה ?)", type: "text", group: "בדיקות" },
  { slug: "digital_signed_map_last_6m", label: "מפה חתומה דיגיטלית חצי שנה אחרונה", type: "boolean", group: "מפות" },
  { slug: "manager_file_number", label: "מס' תיק מנהל", type: "text", group: "מנהל" },
  { slug: "id_number", label: "תז", type: "text", group: "פרטי לקוח" },
  { slug: "committee_fee_invoice", label: "שובר אגרה מהוועדה", type: "boolean", group: "אגרות" },
  { slug: "committee_fee_paid", label: "תשלום אגרה", type: "boolean", group: "אגרות" },
  { slug: "order_existing_permits", label: "להזמין היתרים קיימים", type: "boolean", group: "היתרים" },
  { slug: "mark_extension_on_map", label: "סימון תוספת ע\"ג מפה", type: "boolean", group: "מפות" },
  { slug: "buyers", label: "רוכשים", type: "text", group: "חוזים" },
  { slug: "sale_contract", label: "חוזה מכר", type: "boolean", group: "חוזים" },
  { slug: "info_file_submitted", label: "הוגש תיק מידע", type: "boolean", group: "מידע" },
  { slug: "info_file_received_at", label: "מועד קבלת תיק מידע", type: "text", group: "מידע" },
  { slug: "signed_program", label: "פרוגרמה חתומה", type: "boolean", group: "תכנון" },
  { slug: "columns_and_engineer_opinion", label: "העמדת עמודים וחוו\"ד מהנדס לפרויקט", type: "boolean", group: "תכנון" },
  { slug: "plans", label: "תוכניות", type: "text", group: "תכנון" },
  { slug: "signed_plan", label: "תוכנית חתומה", type: "boolean", group: "תכנון" },
  { slug: "payment_per_contract", label: "תשלום ע\"פ חוזה", type: "text", group: "כספים" },
  { slug: "prepare_gramushka", label: "הכנת גרמושקא", type: "boolean", group: "גרמושקא" },
  { slug: "tabu_extract", label: "נסח טאבו", type: "boolean", group: "מסמכים" },
  { slug: "rights_approval", label: "אישור זכויות", type: "boolean", group: "מסמכים" },
  { slug: "lease_contract", label: "חוזה חכירה", type: "boolean", group: "חוזים" },
  { slug: "committee_signatures_on_gramushka", label: "חתימת וועד ואגודה ע\"ג גרמושקא", type: "boolean", group: "גרמושקא" },
  { slug: "neighbors_signatures_on_gramushka", label: "חתימת שכנים ע\"ג גרמושקא", type: "boolean", group: "גרמושקא" },
  { slug: "adjacent_neighbor_signature_shared_fences", label: "חתימת שכן גובל בגדרות משותפים", type: "boolean", group: "גרמושקא" },
  { slug: "min_agri_approval", label: "אישור משרד החקלאות", type: "boolean", group: "אישורים" },
  { slug: "forester_approval", label: "אישור פקיד היערות", type: "boolean", group: "אישורים" },
  { slug: "complete_application_engineer_signature", label: "השלמת בקשה והחתמת מהנדסת", type: "boolean", group: "אישורים" },
  { slug: "antiquities_poa_signed", label: "רשות העתיקות - ייפוי כח חתום אישור", type: "boolean", group: "אישורים" },
  { slug: "regular_permit_process", label: "הליך היתר רגיל", type: "boolean", group: "היתרים" },
  { slug: "deposit_invoice", label: "שובר פקדון לתשלום", type: "boolean", group: "אגרות" },
  { slug: "relief_permit_publication", label: "הליך היתר בהקלה - קבלת נוסח פרסום", type: "boolean", group: "היתרים" },
  { slug: "publish_details_in_rishui", label: "הזנת פרטי הפרסום ברשוי", type: "boolean", group: "היתרים" },
  { slug: "geg_mamad_plan_for_engineer", label: "הגא - הכנת תוכנית ממד למהנדס", type: "boolean", group: "תכנון" },
  { slug: "permit_with_conditions", label: "היתר בתנאים", type: "boolean", group: "היתרים" },
];