import { createClientFromRequest } from 'npm:@base44/sdk@0.5.0';

const CLIENT_ID = Deno.env.get("GOOGLE_CLIENT_ID");
const CLIENT_SECRET = Deno.env.get("GOOGLE_CLIENT_SECRET");

// Build redirect URI dynamically
function buildRedirectUri(req) {
  const url = new URL(req.url);
  const host = req.headers.get("x-forwarded-host") || url.host;
  const proto = req.headers.get("x-forwarded-proto") || url.protocol.replace(":", "") || "https";
  return `${proto}://${host}/AuthCallback`;
}

Deno.serve(async (req) => {
  const base44 = createClientFromRequest(req);

  try {
    const isAuth = await base44.auth.isAuthenticated();
    if (!isAuth) {
      return Response.json({ ok: false, error: "Unauthorized" }, { status: 401 });
    }

    if (!CLIENT_ID || !CLIENT_SECRET) {
      return Response.json({
        ok: false,
        error: "Missing GOOGLE_CLIENT_ID or GOOGLE_CLIENT_SECRET",
        hint: "Set both env vars in Base44 settings"
      }, { status: 500 });
    }

    const REDIRECT_URI = buildRedirectUri(req);

    // Intentionally use invalid code; check error type
    const params = new URLSearchParams();
    params.set("client_id", CLIENT_ID);
    params.set("client_secret", CLIENT_SECRET);
    params.set("redirect_uri", REDIRECT_URI);
    params.set("grant_type", "authorization_code");
    params.set("code", "dummy_invalid_code_123");

    const res = await fetch("https://oauth2.googleapis.com/token", {
      method: "POST",
      headers: { "Content-Type": "application/x-www-form-urlencoded" },
      body: params.toString()
    });

    const body = await res.json().catch(() => ({}));

    let outcome;
    const err = (body?.error || "").toLowerCase();
    if (err === "invalid_grant") {
      outcome = {
        config_ok: true,
        summary: "Client ID/Secret accepted by Google (invalid_grant is expected with dummy code).",
        next: "If your real exchange still fails, ensure the code was generated by the same client and the exact redirect URI."
      };
    } else if (err === "invalid_client" || err === "unauthorized_client") {
      outcome = {
        config_ok: false,
        summary: "Google rejected the client credentials (invalid_client/unauthorized_client).",
        hint: "Verify client type is Web application, Secret is correct, and you updated GOOGLE_CLIENT_ID/SECRET."
      };
    } else {
      outcome = {
        config_ok: false,
        summary: "Unexpected response from Google."
      };
    }

    return Response.json({
      ok: true,
      client_id_hint: CLIENT_ID ? `${CLIENT_ID.slice(0, 4)}...${CLIENT_ID.slice(-6)}` : null,
      redirect_uri_used: REDIRECT_URI,
      google_response: body,
      ...outcome
    }, { status: 200 });
  } catch (e) {
    return Response.json({ ok: false, error: e?.message || String(e) }, { status: 500 });
  }
});